### PR TITLE
Update for MessagePacket to TextPacket

### PR DESCRIPTION
**Pull request by PEMapModder**

### CODE REVIEW

**Comment by PEMapModder** [comment]
This doesn't seem to work yet. I am checking why.

**Comment by PEMapModder** [comment]
Test result:

> s s adum
> 11:11:18 [INFO] adum[/SPECTER:19133] logged in with entity id 1 at (world, -91, 7, 429)
> 11:11:18 [INFO] [Specter] Message to adum: You have been authenticated by matching the last IP authenticated with.
> 11:11:18 [INFO] [Specter] Message to adum: Welcome to LegionPE.
> 11:11:18 [INFO] [Specter] Message to adum: Walk into a portal or open your inventory and choose an item to join a game.
> 11:11:18 [INFO] [Specter] Message to adum: Limited 25% discount on all ranks ending on Friday! View them here: www.legionpvp.eu
> 11:11:18 [INFO] Session started.
> s s bdum
> 11:11:21 [INFO] bdum[/SPECTER:19133] logged in with entity id 2 at (world, -91, 7, 429)
> 11:11:21 [INFO] [Specter] Message to bdum: You have been authenticated by matching the last IP authenticated with.
> 11:11:21 [INFO] [Specter] Message to bdum: Welcome to LegionPE.
> 11:11:21 [INFO] [Specter] Message to bdum: Walk into a portal or open your inventory and choose an item to join a game.
> 11:11:21 [INFO] [Specter] Message to bdum: Limited 25% discount on all ranks ending on Friday! View them here: www.legionpvp.eu
> 11:11:21 [INFO] Session started.
> s c a test
> 11:11:28 [INFO] [Specter] Sent packet.
> say Test
> 11:11:34 [INFO] [Server] Test
> 11:11:34 [INFO] [Specter] Message to adum: %chat.type.announcement
> 11:11:34 [INFO] [Specter] Message to bdum: %chat.type.announcement
> 11:11:44 [DEBUG] Level "world_spleef" took 63.8ms, setting tick rate to 2 ticks
> 11:11:44 [DEBUG] Raising level "world_spleef" tick rate to 1 ticks
> s c a /help
> 11:12:13 [INFO] [Specter] Sent packet.

**Comment by Falkirks** [comment]
So not working yet?

**Comment by PEMapModder** [comment]
Message echo works, but `/s c` doesn't seem to work.

**Comment by Falkirks** [comment]
Is this ready to be merged?

**Comment by PEMapModder** [comment]
Test it. I don't think message echoing works. But at least it improves things not breaks things afaik

**Pull request merged**
