### PR TITLE
Small addition

### PR DESCRIPTION
**Pull request by Gamecrafter**
Well, since this can be added, why shouldn't it? :stuck_out_tongue:

### CODE REVIEW

**Comment by PEMapModder** [comment]
Why `19133`?
This is only used internally, not anywhere else.

**Comment by Gamecrafter** [comment]
Well, I don't know about you. The default Specter port is `19133`.

**Comment by PEMapModder** [comment]
I guess this is OK to merge.

**Comment by Falkirks** [comment]
Merging this. Let me know if there are issues.

**Pull request merged**
