### PR TITLE
Updated type declaration

### LINKED ISSUE #54: Plugin won't load.
I get this error every time I try to start my server with specter:
```
Fatal error: Declaration of specter\network\SpecterInterface::setName($name) must be compatible with pocketmine\network\SourceInterface::setName(string $name) in /home/hittmana/Pocketmine/plugins/Specter-master 2/src/specter/network/SpecterInterface.php on line 24
```

### PR DESCRIPTION
**Pull request by Thunder33345**
should fix #54 theoretically

### CODE REVIEW

**Comment by SOF3** [comment]
API version?

**Comment by dktapps** [comment]
> 3.0.0-ALPHA6 (unreleased dev version)

**Comment by Falkirks** [comment]
I like to keep this working against the latest dev builds whenever possible, so I will merge.

**Comment by SOF3** [comment]
Update the API version in plugin.yml

**Comment by dktapps** [comment]
@SOF3 there's a ton of other things that will need fixing for ALPHA7 here. I'll make a PR later if nobody beats me to it.

**Pull request merged**
