### PR TITLE
Update to Minecraft 1.14

### PR DESCRIPTION
**Pull request by thebigsmileXD**

### CODE REVIEW

**Comment by SOF3** [comment]
Considering @falkirks is no longer active with PocketMine plugins, if you want to maintain a fork, I'm OK with transferring the Poggit plugin ownership to you. (The Specter MIT license should have no problem with this)

**Comment by falkirks** [comment]
@thebigsmileXD (cc @SOF3) You are totally welcome to do so under the terms of the MIT license which means including the license file with any distributed binaries. I am also happy to add you on to this repo, so you don't need to do a fork.

**Comment by thebigsmileXD** [comment]
> I am also happy to add you on to this repo, so you don't need to do a fork.
This would be cool, that way we could keep the users

**Comment by falkirks** [comment]
@thebigsmileXD done! You should be able to tag releases on poggit too (not exactly sure how poggit works). Let me know if there is anything else I can do to help.

**Comment by thebigsmileXD** [comment]
> You should be able to tag releases on poggit too

I have to figure out that one now

**Comment by SOF3** [comment]
Some bugs with release permissions checking, resolved by hardcoding links.

**Pull request merged**
