### PR TITLE
Log and quit upon being transferred

### PR DESCRIPTION
**Pull request by PEMapModder**

### CODE REVIEW

**Comment by Falkirks** [comment]
Awesome!

**Comment by Gamecrafter** [comment]
Wait, so specters can be transferred now?

**Comment by PEMapModder** [comment]
They will leave the game, but they of course won't transfer. Just read the code :P

**Comment by Gamecrafter** [comment]
Obviously I read the code, I wanted to make sure they couldn't be transferred, people could slam players to other servers if specters could be transferred.

**Comment by PEMapModder** [comment]
@Gamecrafter specters are just "players connected using console through PHP" (just like BigBrother connected "using MCPC through TCP" and normal players connected "using MCPE through UDP". Specter basically does no external networking. How can they join other servers? :grin: 

And it would be great if we can bot them using three lines of code :smirk:

**Pull request merged**
